# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
#    loaders:
#        default:
#            filesystem:
#                data_root: "%kernel.project_dir%/public"
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#    cache: default
#    data_loader: default
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound
