vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /produits/image
            upload_destination: '%kernel.project_dir%/public/produits/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
